global:
  scrape_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # - job_name: 'node_exporter'
  #   static_configs:
  #     - tagets: ['localhost:9100']

  - job_name: 'yandex_cloud'
    file_sd_configs:
      - files:
        - '/etc/prometheus/targets.json'
    metrics_path: '/metrics'
    scheme: 'http'
    relabel_configs:
      - source_labels: [instance]
        target_label: instance

rule_files:
  - "/etc/prometheus/alerts.yml"
